"""initial durable review platform schema

Revision ID: 20260905_0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "20260905_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("release_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dialogue_policy_versions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("codec_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
    )
    op.create_table(
        "model_profile_versions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("codec_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill_versions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("codec_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
    )
    op.create_table(
        "model_profile_availability",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("model_profile_id", sa.String(), nullable=False),
        sa.Column("model_profile_version", sa.String(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_profile_id", "model_profile_version"],
            ["model_profile_versions.id", "model_profile_versions.version"],
        ),
        sa.PrimaryKeyConstraint("deployment_id", "model_profile_id", "model_profile_version"),
    )
    op.create_table(
        "workspaces",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "id"),
    )
    op.create_table(
        "actors",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_table(
        "artifacts",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("store_key", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("canonical_codec_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(kind = 'report_canonical' AND canonical_codec_id = 'jcs-rfc8785-0.1.4') OR (kind <> 'report_canonical' AND canonical_codec_id IS NULL)",
            name="artifact_codec_matches_kind",
        ),
        sa.CheckConstraint("size_bytes >= 0", name="artifact_nonnegative_size"),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "store_key", "sha256"),
        sa.UniqueConstraint("store_key"),
    )
    op.create_table(
        "execution_snapshots",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("codec_id", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "digest"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("codec_id", sa.String(length=64), nullable=False),
        sa.Column("resource_kind", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "operation", "key"),
    )
    op.create_table(
        "job_outbox",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("business_key", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "business_key"),
    )
    op.create_table(
        "review_profile_families",
        sa.Column("row_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("deployment_id", sa.String(length=36), nullable=True),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope = 'system' AND deployment_id IS NOT NULL AND organization_id IS NULL AND workspace_id IS NULL) OR (scope = 'workspace' AND deployment_id IS NULL AND organization_id IS NOT NULL AND workspace_id IS NOT NULL)",
            name="review_profile_family_exact_owner",
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("row_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "document_versions",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("extraction_state", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "artifact_id"],
            ["artifacts.organization_id", "artifacts.workspace_id", "artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "created_by"],
            ["actors.organization_id", "actors.workspace_id", "actors.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_table(
        "review_profile_versions",
        sa.Column("family_row_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("semantic_digest", sa.String(length=64), nullable=False),
        sa.Column("semantic_codec_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("supersedes_version", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_row_id"],
            ["review_profile_families.row_id"],
        ),
        sa.PrimaryKeyConstraint("family_row_id", "version"),
        sa.UniqueConstraint("family_row_id", "semantic_digest"),
    )
    op.create_table(
        "document_extractions",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("parser_name", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("settings_digest", sa.String(length=64), nullable=False),
        sa.Column("settings_codec_id", sa.String(length=64), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("safe_error_message", sa.String(length=512), nullable=True),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("checkpoint", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending','extracting','completed','partial','failed')",
            name="document_extraction_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "document_id"],
            ["document_versions.organization_id", "document_versions.workspace_id", "document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_table(
        "review_profile_heads",
        sa.Column("family_row_id", sa.String(length=36), nullable=False),
        sa.Column("head_version", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_row_id", "head_version"],
            ["review_profile_versions.family_row_id", "review_profile_versions.version"],
        ),
        sa.ForeignKeyConstraint(
            ["family_row_id"],
            ["review_profile_families.row_id"],
        ),
        sa.PrimaryKeyConstraint("family_row_id"),
    )
    op.create_table(
        "review_runs",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued','preparing','reviewing','validating','completed','failed','cancelled')",
            name="review_run_state",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "document_id"],
            ["document_versions.organization_id", "document_versions.workspace_id", "document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["workspaces.organization_id", "workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_table(
        "fragments",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("extraction_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "document_id"],
            ["document_versions.organization_id", "document_versions.workspace_id", "document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "extraction_id"],
            [
                "document_extractions.organization_id",
                "document_extractions.workspace_id",
                "document_extractions.id",
            ],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "document_id", "ordinal"),
    )
    op.create_table(
        "review_reports",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("canonical_sha256", sa.String(length=64), nullable=False),
        sa.Column("etag", sa.String(length=66), nullable=False),
        sa.Column("codec_id", sa.String(length=64), nullable=False),
        sa.Column("graph", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "artifact_id"],
            ["artifacts.organization_id", "artifacts.workspace_id", "artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "run_id"],
            ["review_runs.organization_id", "review_runs.workspace_id", "review_runs.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "review_run_executions",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("checkpoint", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "run_id"],
            ["review_runs.organization_id", "review_runs.workspace_id", "review_runs.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "review_run_sources",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("prepared", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "document_id"],
            ["document_versions.organization_id", "document_versions.workspace_id", "document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "run_id"],
            ["review_runs.organization_id", "review_runs.workspace_id", "review_runs.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "run_id", "source_id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "run_id", "ordinal"),
    )
    op.create_table(
        "source_diagnostics",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("extraction_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("safe_message", sa.String(length=512), nullable=False),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "extraction_id"],
            [
                "document_extractions.organization_id",
                "document_extractions.workspace_id",
                "document_extractions.id",
            ],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "extraction_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "extraction_id", "ordinal"),
    )
    op.create_table(
        "findings",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("report_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "report_id"],
            ["review_reports.organization_id", "review_reports.workspace_id", "review_reports.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "report_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "report_id", "ordinal"),
    )
    op.create_table(
        "report_coverage",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "report_id"],
            ["review_reports.organization_id", "review_reports.workspace_id", "review_reports.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "report_id"),
    )
    op.create_table(
        "report_provenance",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "report_id"],
            ["review_reports.organization_id", "review_reports.workspace_id", "review_reports.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "report_id"),
    )
    op.create_table(
        "review_work_items",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("fragment_id", sa.String(length=160), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "execution_id"],
            [
                "review_run_executions.organization_id",
                "review_run_executions.workspace_id",
                "review_run_executions.id",
            ],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "execution_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "execution_id", "ordinal"),
        sa.UniqueConstraint("organization_id", "workspace_id", "id"),
    )
    op.create_table(
        "finding_anchors",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "finding_id"],
            ["findings.organization_id", "findings.workspace_id", "findings.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "finding_id", "ordinal"),
    )
    op.create_table(
        "finding_dialogues",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "finding_id"],
            ["findings.organization_id", "findings.workspace_id", "findings.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("finding_id"),
    )
    op.create_table(
        "finding_states",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("decision_revision", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "finding_id"],
            ["findings.organization_id", "findings.workspace_id", "findings.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "finding_id"),
    )
    op.create_table(
        "human_decisions",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "finding_id"],
            ["findings.organization_id", "findings.workspace_id", "findings.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "finding_id", "revision"),
    )
    op.create_table(
        "model_attempts",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "work_item_id"],
            ["review_work_items.organization_id", "review_work_items.workspace_id", "review_work_items.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "work_item_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "work_item_id", "ordinal"),
    )
    op.create_table(
        "dialogue_turns",
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dialogue_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dialogue_id"],
            ["finding_dialogues.organization_id", "finding_dialogues.workspace_id", "finding_dialogues.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "dialogue_id", "ordinal"),
    )
    op.create_index(
        "uq_active_dialogue_turn",
        "dialogue_turns",
        ["organization_id", "workspace_id", "dialogue_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('queued', 'generating')"),
    )
    op.create_table(
        "generation_attempts",
        sa.Column("dialogue_turn_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("checkpoint", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dialogue_turn_id"],
            ["dialogue_turns.organization_id", "dialogue_turns.workspace_id", "dialogue_turns.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "workspace_id", "id"),
        sa.UniqueConstraint("organization_id", "workspace_id", "dialogue_turn_id", "ordinal"),
    )
    # These relations are the audit trail and reproducibility boundary.  Their
    # rows are append-only; mutable workflow state lives in the corresponding
    # *_state, *_head, execution, availability, and outbox tables instead.
    op.execute(
        """
        CREATE FUNCTION reject_immutable_row_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'immutable relation % does not allow %', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$
        """
    )
    immutable_relations = (
        "deployments",
        "dialogue_policy_versions",
        "model_profile_versions",
        "skill_versions",
        "artifacts",
        "execution_snapshots",
        "idempotency_records",
        "document_versions",
        "review_profile_versions",
        "fragments",
        "source_diagnostics",
        "review_reports",
        "review_run_sources",
        "findings",
        "finding_anchors",
        "report_coverage",
        "report_provenance",
        "human_decisions",
    )
    for relation in immutable_relations:
        op.execute(
            f"CREATE TRIGGER reject_mutation BEFORE UPDATE OR DELETE ON {relation} "
            "FOR EACH ROW EXECUTE FUNCTION reject_immutable_row_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generation_attempts")
    op.drop_index(
        "uq_active_dialogue_turn",
        table_name="dialogue_turns",
        postgresql_where=sa.text("state IN ('queued', 'generating')"),
    )
    op.drop_table("dialogue_turns")
    op.drop_table("model_attempts")
    op.drop_table("human_decisions")
    op.drop_table("finding_states")
    op.drop_table("finding_dialogues")
    op.drop_table("finding_anchors")
    op.drop_table("review_work_items")
    op.drop_table("report_provenance")
    op.drop_table("report_coverage")
    op.drop_table("findings")
    op.drop_table("source_diagnostics")
    op.drop_table("review_run_sources")
    op.drop_table("review_run_executions")
    op.drop_table("review_reports")
    op.drop_table("fragments")
    op.drop_table("review_runs")
    op.drop_table("review_profile_heads")
    op.drop_table("document_extractions")
    op.drop_table("review_profile_versions")
    op.drop_table("document_versions")
    op.drop_table("review_profile_families")
    op.drop_table("job_outbox")
    op.drop_table("idempotency_records")
    op.drop_table("execution_snapshots")
    op.drop_table("artifacts")
    op.drop_table("actors")
    op.drop_table("workspaces")
    op.drop_table("model_profile_availability")
    op.drop_table("skill_versions")
    op.drop_table("organizations")
    op.drop_table("model_profile_versions")
    op.drop_table("dialogue_policy_versions")
    op.drop_table("deployments")
    op.execute("DROP FUNCTION reject_immutable_row_mutation()")
    # ### end Alembic commands ###
