"""Render the guest deployment contract from unchanged trusted-v1 payload schemas."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]


def guest_contract() -> dict:
    schema = yaml.safe_load((ROOT / "contracts/review-platform/v1/openapi.yaml").read_text())
    schema["info"].update(
        title="Review Platform Guest API",
        version="1.2.0",
        description=(
            "Guest deployment of the trusted-v1 payload contract. GET /v1/bootstrap creates or "
            "restores an isolated browser workspace using an opaque HttpOnly Secure SameSite=Lax "
            "cookie. The cookie expires after 30 days without use; stored data is not deleted. "
            "All workspace operations require a valid guest session. A workspace ID alone does "
            "not authorize access. See guest-v1/README.md for lifecycle and storage limits."
        ),
    )
    schema["security"] = [{"GuestSession": []}]
    schema["components"]["securitySchemes"] = {
        "GuestSession": {"type": "apiKey", "in": "cookie", "name": "review_guest"}
    }
    problem = {"content": {"application/problem+json": {"schema": {"$ref": "#/components/schemas/Problem"}}}}
    for path, item in schema["paths"].items():
        for verb in ("get", "post", "put", "delete", "patch"):
            if verb not in item:
                continue
            operation = item[verb]
            if path == "/v1/bootstrap":
                operation["security"] = []
                operation["summary"] = "Create or restore the browser's guest workspace"
                operation["responses"]["200"]["headers"] = {
                    "Set-Cookie": {
                        "description": (
                            "Opaque review_guest cookie; HttpOnly, Secure, SameSite=Lax, "
                            "Path=/; Max-Age=2592000."
                        ),
                        "schema": {"type": "string"},
                    }
                }
            else:
                operation["responses"]["401"] = {
                    "description": "Missing, invalid or expired guest session (guest_session_required).",
                    **deepcopy(problem),
                }
            operation["responses"]["403"] = {
                "description": "Browser cross-origin request rejected (cross_origin_forbidden).",
                **deepcopy(problem),
            }
    for upload_path in (
        "/v1/workspaces/{workspaceId}/documents",
        "/v1/workspaces/{workspaceId}/document-families/{familyId}/versions",
    ):
        upload = schema["paths"][upload_path]["post"]["responses"]
        upload["413"] = {
            "description": (
                "File limit or guest storage quota exceeded (payload_too_large / guest_storage_limit)."
            ),
            **deepcopy(problem),
        }
        upload["503"] = {
            "description": (
                "Total guest upload budget or disk reserve reached (storage_unavailable). "
                "Existing files remain readable."
            ),
            **deepcopy(problem),
        }
    return schema


if __name__ == "__main__":
    target = ROOT / "contracts/review-platform/guest-v1/openapi.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "# Generated by tools/contracts/build_guest_contract.py; do not edit manually.\n"
        + yaml.safe_dump(guest_contract(), sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
